# Defines the options for building the project on linux with Travis-CI
# For more configuration options, see the wiki:
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
sudo: required
dist: trusty
warnings_are_errors: true

env:
   global:
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false
   

repos:
  CRAN: https://cran.rstudio.com
  GRAN: https://owi.usgs.gov/R

before_script:
  - Rscript -e "install.packages('knitr')"
  - Rscript -e "install.packages('rmarkdown')"

r_packages:
 - modeest
 - deSolve
 - rstan

r_github_packages:
 - jimhester/covr
 - GLEON/LakeMetabolizer

script:
  - |
    R CMD build ${R_BUILD_ARGS} .
    PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    travis_wait 40 R CMD check ${R_CHECK_ARGS} "${PKG_FILE_NAME}"

after_success:
  - if [[ "${R_CODECOV}" ]]; then travis_wait 20 R -e 'covr::coveralls()'; fi

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
