# Defines the options for building the project on linux with Travis-CI
# For more configuration options, see the wiki:
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
sudo: required
warnings_ar_errors: true

repos:
  CRAN: https://cloud.r-project.org
  GRAN: http://owi.usgs.gov/R

before_install:
  - wget https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Source/JAGS-4.2.0.tar.gz
  - tar xfvs JAGS-4.2.0.tar.gz
  - cd JAGS-4.2.0
  - sudo ./configure
  - sudo make
  - sudo make install
  - cd ..
  - sudo rm -f JAGS-4.2.0.tar.gz
  - sudo rm -rf JAGS-4.2.0

before_script:
  - Rscript -e "install.packages('knitr', repos='http://cran.cnr.Berkeley.edu/')"
  - Rscript -e "install.packages('rmarkdown', repos='http://cran.cnr.Berkeley.edu/')"

r_packages:
 - modeest

r_github_packages:
 - jimhester/covr
 - GLEON/LakeMetabolizer

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
